CREATE DATABASE MY_COLLEGE;
USE MY_COLLEGE;

CREATE TABLE STUDENT(
NAME VARCHAR (100),
Roll_NO INT primary KEY,
COURSE VARCHAR (50),
SECTION int 
);
select * FROM STUDENT;

INSERT INTO STUDENT
(NAME,ROLL_NO,COURSE,SECTION)
VALUES
 ("KARAN",10,"BCA",33),
("ARJUN",11,"BCA",33),
("ANUJ",12,"BCADS",31);
INSERT INTO STUDENT (NAME,ROLL_NO,COURSE,SECTION) VALUES
("ARJUN", 21, "BCA", 33),
("ANUJ", 22, "BCADS", 31);


 
 
 
 
